apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot
  name: springboot-server
spec:
  selector:
    matchLabels:
      app: springboot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springboot
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: springboot-gcs-key
      containers:
      - image: asia.gcr.io/able-groove-288900/argo
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        name: server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      securityContext: {}
      terminationGracePeriodSeconds: 30
