apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot
  name: springboot-svc

spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot
  sessionAffinity: None
  type: LoadBalancer